services:
  backend:
    build: ./backend
    container_name: food_backend
    ports:
      - "8030:8000"
    volumes:
      - ./backend:/code
      - ./backend/audios:/code/audios
    environment:
      - REDIS_URL=redis://redis:6379
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    networks:
      - food-network
    links:
      - "redis:redis"

  # frontend:
  #   build: ./frontend
  #   container_name: food_frontend
  #   ports:
  #     - "4001:3000"
  #   volumes:
  #     - ./frontend:/app
  #   stdin_open: true
  #   tty: true

  redis:
    image: redis:alpine
    container_name: food_redis
    ports:
      - "6382:6379"
    volumes:
      - redis_data:/data
    networks:
      - food-network

networks:
  food-network:
    driver: bridge

volumes:
  redis_data: