services:
  backend:
    build: ./backend
    container_name: food_backend
    ports:
      - "8030:8000"
    volumes:
      - ./backend:/code
      - ./backend/audios:/code/audios
    environment:
      - REDIS_URL=redis://redis:6379
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    networks:
      - food-network
    links:
      - "redis:redis"

  frontend:
    build: ./frontend
    container_name: food_frontend
    ports:
      - "4001:3000"
    volumes:
      # Use bind mount with delegated consistency for better performance
      - type: bind
        source: ./frontend
        target: /app
        consistency: delegated
      - /app/node_modules
      - /app/.next
    environment:
      # Turbopack polling - try different values
      - TURBOPACK_POLL=500
      # Fallback environment variables
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NEXT_TELEMETRY_DISABLED=1
      # Force file watching
      - FORCE_COLOR=1
    stdin_open: true
    tty: true
    networks:
      - food-network
    depends_on:
      - backend

  redis:
    image: redis:alpine
    container_name: food_redis
    ports:
      - "6382:6379"
    volumes:
      - redis_data:/data
    networks:
      - food-network

networks:
  food-network:
    driver: bridge

volumes:
  redis_data: