services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: nomtok_backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=core.settings
    env_file:
      - .env.prod
    networks:
      - nomtok_network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/dashboard/"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: nomtok_frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=/
    env_file:
      - .env.prod
    depends_on:
      - backend
    networks:
      - nomtok_network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 40s

networks:
  nomtok_network:
    driver: bridge