services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: nomtok_backend_prod
    ports:
      - "8030:8000"
    environment:
      - REDIS_URL=redis://redis:6379
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/cookies:/code/cookies
      - ./backend/logs:/code/logs
    depends_on:
      - redis
      - tor
    networks:
      - nomtok-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args: # Add this section
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    container_name: nomtok_frontend_prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - nomtok-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 40s

  redis:
    image: redis:alpine
    container_name: nomtok_redis_prod
    ports:
      - "6382:6379"
    volumes:
      - redis_data:/data
    networks:
      - nomtok-network
    restart: always

  tor:
    image: peterdavehello/tor-socks-proxy:latest  # Or pin a version like :0.4.8.12
    container_name: nomtok_tor_prod
    networks:
      - nomtok-network
    restart: unless-stopped

  bgutil-provider:
    image: brainicism/bgutil-ytdlp-pot-provider:latest
    container_name: nomtok_bgutil_provider_prod
    ports:
      - "4416:4416"
    networks:
      - nomtok-network
    restart: unless-stopped
    init: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4416/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  nomtok-network:
    driver: bridge

volumes:
  redis_data: