services:
  backend:
    build: ./backend
    container_name: food_backend
    ports:
      - "8030:8000"
    volumes:
      - ./backend:/code
      - ./backend/audios:/code/audios
    environment:
      - REDIS_URL=redis://redis:6379
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    networks:
      - nomtok-network
    links:
      - "redis:redis"

  tor:
    image: peterdavehello/tor-socks-proxy:latest  # Or pin a version like :0.4.8.12
    container_name: tor-proxy
    networks:
      - nomtok-network
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: food_redis
    ports:
      - "6382:6379"
    volumes:
      - redis_data:/data
    networks:
      - nomtok-network

networks:
  nomtok-network:
    driver: bridge

volumes:
  redis_data: