services:
  backend:
    build: ./backend
    container_name: food_backend
    ports:
      - "8030:8000"
    volumes:
      - ./backend:/code
    environment:
      # - DATABASE_URL=postgresql://postgres:postgres@db:5432/tariffhero
      - REDIS_URL=redis://redis:6379
    env_file:
      - ./backend/.env
    depends_on:
      - redis

  # frontend:
  #   build: ./frontend
  #   container_name: food_frontend
  #   ports:
  #     - "4001:3000"
  #   volumes:
  #     - ./frontend:/app
  #   stdin_open: true
  #   tty: true

  redis:
    image: redis:alpine
    container_name: tariffhero_redis
    ports:
      - "6382:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: