FROM python:3.13-slim-bookworm

WORKDIR /code

RUN apt-get update && apt-get install -y ffmpeg

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install gunicorn uvicorn
RUN playwright install --with-deps chromium  # Installs browser + system deps (e.g., libnss3)

COPY . .

EXPOSE 8000

CMD ["gunicorn", "-w", "2", "app.main:app", "-k", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000", "--timeout", "120"]