"""altered_processed_to_is_processed

Revision ID: 17e2dd4a3c68
Revises: d3e1b2825f1e
Create Date: 2025-10-05 17:22:18.484244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17e2dd4a3c68'
down_revision: Union[str, Sequence[str], None] = 'd3e1b2825f1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('is_processed', sa.Boolean(), server_default='false', nullable=False))
    op.drop_column('videos', 'processed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('processed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('videos', 'is_processed')
    # ### end Alembic commands ###
