"""add_cuisine_and_restaurant_cuisine_table_and_remove_influencer_nationality

Revision ID: 33e3f0a928b6
Revises: 4601034bacbd
Create Date: 2025-09-06 08:23:24.689612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33e3f0a928b6'
down_revision: Union[str, Sequence[str], None] = '4601034bacbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuisines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('restaurant_cuisines',
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('cuisine_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cuisine_id'], ['cuisines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('restaurant_id', 'cuisine_id')
    )
    op.drop_column('influencers', 'country')
    op.drop_column('influencers', 'region')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('influencers', sa.Column('region', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('influencers', sa.Column('country', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_table('restaurant_cuisines')
    op.drop_table('cuisines')
    # ### end Alembic commands ###
