"""added country field

Revision ID: 4601034bacbd
Revises: 51077bafe991
Create Date: 2025-09-04 15:03:12.120035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4601034bacbd'
down_revision: Union[str, Sequence[str], None] = '51077bafe991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('influencers', sa.Column('country', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('influencers', 'country')
    # ### end Alembic commands ###
