"""updated restaurant model with business status

Revision ID: 6b7c6afd98e4
Revises: 8bbfc22ddab9
Create Date: 2025-08-02 07:19:42.293973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b7c6afd98e4'
down_revision: Union[str, Sequence[str], None] = '8bbfc22ddab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('business_status', sa.String(length=50), server_default='BUSINESS_STATUS_UNSPECIFIED', nullable=False))
    op.drop_column('restaurants', 'live_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('live_status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('restaurants', 'business_status')
    # ### end Alembic commands ###
