"""add timestamp column to listings table

Revision ID: 781380e27f0c
Revises: 33e3f0a928b6
Create Date: 2025-09-21 14:06:09.899505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '781380e27f0c'
down_revision: Union[str, Sequence[str], None] = '33e3f0a928b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('timestamp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'timestamp')
    # ### end Alembic commands ###
