"""Add subscriber_count to influencers table

Revision ID: 79383d4d5a62
Revises: 920d05f5a88e
Create Date: 2025-08-20 10:40:55.982000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79383d4d5a62'
down_revision: Union[str, Sequence[str], None] = '920d05f5a88e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('influencers', sa.Column('subscriber_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('influencers', 'subscriber_count')
    # ### end Alembic commands ###
