"""removed branch_name and made restaurant name unique

Revision ID: 873ebfb25739
Revises: 9757514bbb01
Create Date: 2025-08-05 10:58:36.663296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '873ebfb25739'
down_revision: Union[str, Sequence[str], None] = '9757514bbb01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_restaurants_name'), 'restaurants', ['name'], unique=True)
    op.drop_column('restaurants', 'branch_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('branch_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_restaurants_name'), table_name='restaurants')
    # ### end Alembic commands ###
