"""Add banner_url to influencers table

Revision ID: 920d05f5a88e
Revises: 10254ecd09a3
Create Date: 2025-08-20 10:09:50.281667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '920d05f5a88e'
down_revision: Union[str, Sequence[str], None] = '10254ecd09a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('influencers', sa.Column('banner_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('influencers', 'banner_url')
    # ### end Alembic commands ###
