"""Added photo_url in restaurant

Revision ID: 996ebbfc0ea8
Revises: 873ebfb25739
Create Date: 2025-08-11 13:21:28.162709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '996ebbfc0ea8'
down_revision: Union[str, Sequence[str], None] = '873ebfb25739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('photo_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'photo_url')
    # ### end Alembic commands ###
