"""add_advanced_job_tracking_fields

Revision ID: a25d437145a5
Revises: 781380e27f0c
Create Date: 2025-09-26 06:49:08.582689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a25d437145a5'
down_revision: Union[str, Sequence[str], None] = '781380e27f0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('queue_size', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('items_in_progress', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('failed_items', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('max_retries', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('estimated_completion_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('processing_rate', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('cancellation_requested', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('jobs', sa.Column('cancelled_by', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'cancelled_at')
    op.drop_column('jobs', 'cancelled_by')
    op.drop_column('jobs', 'cancellation_requested')
    op.drop_column('jobs', 'last_heartbeat')
    op.drop_column('jobs', 'processing_rate')
    op.drop_column('jobs', 'estimated_completion_time')
    op.drop_column('jobs', 'max_retries')
    op.drop_column('jobs', 'retry_count')
    op.drop_column('jobs', 'failed_items')
    op.drop_column('jobs', 'items_in_progress')
    op.drop_column('jobs', 'queue_size')
    # ### end Alembic commands ###
