"""remove_context_field_from_listing_and_start_by_from_job

Revision ID: d0417b853aeb
Revises: ccc4a59b32ba
Create Date: 2025-10-04 14:21:15.914833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0417b853aeb'
down_revision: Union[str, Sequence[str], None] = 'ccc4a59b32ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'started_by')
    op.drop_column('listings', 'context')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('context', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('started_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
