"""Add processed column to videos table

Revision ID: d3e1b2825f1e
Revises: d0417b853aeb
Create Date: 2025-10-05 15:46:50.347070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3e1b2825f1e'
down_revision: Union[str, Sequence[str], None] = 'd0417b853aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('processed', sa.Boolean(), nullable=True))
    # Set default value for existing records
    op.execute("UPDATE videos SET processed = FALSE WHERE processed IS NULL")
    # Now make the column NOT NULL
    op.alter_column('videos', 'processed', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'processed')
    # ### end Alembic commands ###
